[pytest]

testpaths =
    tests
    api

python_files =
    test_*.py

python_classes =
    Test*

python_functions =
    test_*

markers =
    smoke: Critical tests for quick validation
    regression: Full regression test suite
    ui: UI automation tests
    api: API automation tests
    db: Database validation tests
    security: Security tests